
name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command

      - uses: meeDamian/github-release@0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.3.6
          name: My Creative Name
          body: >
            This release actually changes the fabric of the reality, so be careful 
            while applying, as error in database migration, can irrecoverably wipe 
            some laws of physics.
          gzip: folders
          files: >
            lib/

